services:
  alpn:
    image: nischalstha/alpn-responder:main
    build:
      context: .
      dockerfile: Dockerfile
      target: alpn
    volumes:
      - ./certificates:/etc/nginx/certs
      - .:/opt/app
    ports:
      - 443:443
    env_file:
      - .env
