# services:
#   alpn:
#     image: nischalstha/alpn-responder:main
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     volumes:
#       - ./certificates:/etc/nginx/certs
#       - .:/opt/app
#     ports:
#       - 443:443
#     env_file:
#       - .env

services:
  alpn:
    image: nischalstha/alpn-responder:main
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./certificates:/etc/nginx/certs
      - .:/opt/app
      - ./config:/opt/app/config
      - ./domains.txt:/opt/app/domains.txt
    ports:
      - 443:443
    env_file:
      - .env
