services:
  alpn:
    image: nischalstha/dehydrated-wrapped:main
    build:
      context: .
      dockerfile: Dockerfile
      target: alpn
    volumes:
      - ./certificates:/etc/nginx/certs
      # - .:/opt/app # For development only. Remove on production
    ports:
      - 10443:443
    env_file:
      - .env
